# Generated by Django 3.2.4 on 2021-06-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_answer_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
