# Generated by Django 3.2.4 on 2021-08-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_researchpublicationlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpublicationlist',
            name='name',
            field=models.CharField(max_length=2000),
        ),
    ]
