# Generated by Django 3.2.4 on 2021-08-10 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('introduction', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('scope_of_work', models.TextField(blank=True)),
                ('objective', models.CharField(blank=True, max_length=2000)),
                ('project_duration', models.CharField(blank=True, max_length=100)),
                ('principle_investigator', models.CharField(blank=True, max_length=500)),
                ('co_investigator', models.CharField(blank=True, max_length=500)),
                ('team_members', models.TextField(blank=True)),
                ('advisors', models.TextField(blank=True)),
                ('international_experts', models.TextField(blank=True)),
                ('phd_research_scholars', models.TextField(blank=True)),
                ('funding', models.CharField(blank=True, max_length=100)),
                ('estimated_completion_date', models.DateTimeField(blank=True)),
                ('other_description', models.TextField(blank=True)),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
