# Generated by Django 3.2.4 on 2021-08-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_status_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='estimated_completion_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
