# Generated by Django 3.2.4 on 2021-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_alter_status_estimated_completion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='state_of_project',
            field=models.CharField(default='ongoing', max_length=10),
        ),
    ]
