# Generated by Django 3.2.4 on 2021-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Visions',
            new_name='Mission',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='Missions',
            new_name='Vision',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='vision',
            new_name='mission',
        ),
        migrations.RenameField(
            model_name='vision',
            old_name='mission',
            new_name='vision',
        ),
    ]
