# Generated by Django 3.2.4 on 2021-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0004_auto_20210615_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchteam',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rnd-team-photos/'),
        ),
    ]
