# Generated by Django 3.2.4 on 2021-06-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0005_researchteam_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchTeam',
            new_name='ResearchTeamMember',
        ),
    ]
