# Generated by Django 3.2.4 on 2021-06-15 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0006_rename_researchteam_researchteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_images', models.FileField(blank=True, upload_to='')),
                ('deans_message', models.TextField()),
                ('deans_photos', models.ImageField(blank=True, null=True, upload_to='home-pg-photos/')),
                ('chairmans_message', models.TextField()),
                ('chairmans_photos', models.ImageField(blank=True, null=True, upload_to='home-pg-photos/')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='home-pg-photos/')),
                ('home_content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='other_pages.homepagecontent')),
            ],
        ),
    ]
