# Generated by Django 3.2.4 on 2021-06-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0007_homepagecarouselimage_homepagecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecarouselimage',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='chairmans_photos',
        ),
    ]
