# Generated by Django 3.2.4 on 2021-06-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0009_remove_homepagecontent_carousel_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecontent',
            old_name='deans_photos',
            new_name='chairmans_photo',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='deans_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home-pg-photos/'),
        ),
    ]
