# Generated by Django 3.2.4 on 2021-06-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0010_auto_20210615_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarouselimage',
            name='home_content',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='other_pages.homepagecontent'),
        ),
    ]
