# Generated by Django 3.2.4 on 2021-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0011_alter_homepagecarouselimage_home_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageContent',
            new_name='HomePageMessages',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselimage',
            name='home_content',
        ),
        migrations.RemoveField(
            model_name='homepagecarouselimage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepagecarouselimage',
            name='deans_photo',
            field=models.ImageField(blank=True, null=True, upload_to='home-pg-photos/'),
        ),
    ]
