# Generated by Django 3.2.4 on 2021-06-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other_pages', '0012_auto_20210616_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagecarouselimage',
            old_name='deans_photo',
            new_name='image',
        ),
    ]
