# Generated by Django 3.2.4 on 2021-08-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userprofile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posting_permission',
            field=models.BooleanField(default=False, verbose_name='posting permission'),
        ),
    ]
