# Generated by Django 3.2.4 on 2021-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_posting_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_management_permission',
            field=models.BooleanField(default=False, verbose_name='project management permission'),
        ),
    ]
